# Generated by Django 4.0.2 on 2022-02-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField(blank=True)),
                ('validate_date', models.DateTimeField(blank=True)),
                ('value', models.FloatField(blank=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_id', to='customer.customervehicles')),
            ],
        ),
    ]
