# Generated by Django 4.0.2 on 2022-02-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customervehicles_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('validate_date', models.DateField()),
                ('value', models.FloatField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customervehicles')),
            ],
        ),
    ]
