# Generated by Django 4.0.2 on 2022-02-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='exit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
