# Generated by Django 4.0.2 on 2022-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational', '0002_alter_parkmovement_exit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='validate_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
