# Generated by Django 4.0.2 on 2022-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational', '0005_alter_parkmovement_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkmovement',
            name='plate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
