# Generated by Django 4.0.2 on 2022-02-14 18:10

import customer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customervehicles_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervehicles',
            name='plate',
            field=customer.models.UpperCaseCharField(max_length=10),
        ),
    ]
